<div style="background: #fff; padding: 5px">
<h2>
			CHILI POWDER
			International export 
			</h2>
			For Grade “A” product, (for export), the Chilli has a bright red stem and is firm to the touch.
We pick the product from our farms, sort into Grades “A”, “B” and “C”. Grade “A” is for export, grades “B” and “C” are for domestic use only.
Our Chili is the cheapest and highest quality anywhere in Asia and beyond.

            <center>
            	<img src="<?php echo BASE_URL ?>/public/images/chili.jpg">
            </center>
</div>