<div style="background: #fff; padding: 5px">
<h2>
			COFFE BEAN/POWDER
			International export 
			</h2>
			Coffee is one of Vietnam's most important agricultural exports. Vietnam is highly competitive as a coffee producer because of ideal climate and enviromental conditions, low production costs, and yields among the highest in the world.

            <center>
            	<img src="<?php echo BASE_URL ?>/public/images/coffee.jpg">
            </center>
</div>