<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/editor/ckeditor.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				}
					 
				 
			});
	
});
</script>
<div class="login_form">

        <div class="goback"><a href="<?php echo $this->url('brochure') ?>">&larr;</a></div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
        <div class="login_body">
          <h1>CẬP NHẬT THÔNG TIN BROCHURE</h1>
              <form id="edit" method="post" action="" enctype="multipart/form-data">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Tiêu đề brochure</td>
                        <td><input type="text" id="brochure_title" name="brochure_title" tabindex="1" value="<?php echo $brochure->brochure_title ?>" autofocus ></td>
                        
                    </tr>
                    
                    <tr>
                        <td>Mô tả </td>
                        <td>
                          <textarea name="brochure_description" id="brochure_description" tabindex="2" ><?php echo $brochure->brochure_description ?></textarea>
                        </td>
                    </tr>
                    <tr>
                      <td></td>
                      <td>
                        <img src="<?php echo BASE_URL ?>/public/images/upload/<?php echo $brochure->brochure_image ?>" width="100px" height="100px">
                      </td>
                    </tr>
                    <tr>
                        <td>Hình đại diện mới </td>
                        <td><input type="file" id="brochure_image" name="brochure_image" tabindex="3" ></td>
                    </tr>
                    
                     <tr>
                        <td ><input type="reset" name="reset" value="Nhập lại" tabindex="5"></td>
                         <td><input type="submit" name="submit" value="Hoàn tất" tabindex="4"></td>
                         
                    </tr>
                </table> 
            </form>
        </div>
        
        </div>

<script type="text/javascript">
  CKEDITOR.replace('brochure_description');
</script>