<div style="background: #fff; padding: 5px">
<h2>
			VIETNAMESE TEA
			International export 
			</h2>
			Vietnamese tea is exported to 61 countries in the world. The production of tea requires great care and craftsmanship. The freshly plucked leaves are carefully and gently proccessed every step of the way...

            <center>
            	<img src="<?php echo BASE_URL ?>/public/images/tea.jpg">
            </center>
</div>