
<?php
$url_order = 'DESC';
if ($order_by == 'video_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
if ($order_by == 'video_link')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'video_description')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> DANH SÁCH VIDEO </h1></center>
<div class="add-box"><a class="add_button" href="<?php
echo $this->url('video/add');
?>">Thêm video mới</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
    
    	
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>
      </div>
   
<table class="table_data">
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','video_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'video_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','video_link','<?php echo $url_order ?>')">Video <?php if ($order_by == 'video_link'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','video_title','<?php echo $url_order ?>')">Tiêu đề <?php if ($order_by == 'video_title'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','video_description','<?php echo $url_order ?>')">Mô tả <?php if ($order_by == 'video_description'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
            
           
        <th>&nbsp;</th>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($videos as $video) : ?>
        <tr id="<?php echo $video->video_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $video->video_id ?>"></td>
            <td><?php echo $i++; ?></td>
            <td>
                <embed allowfullscreen="true" allowscriptaccess="always" flashvars="duration=509&amp;file=<?php echo BASE_URL ?>/public/files/<?php echo $video->video_link; ?>&amp;title=dasdasda&amp;autostart=false&amp;repeat=always&amp;image=<?php echo BASE_URL ?>/public/images/startImg.jpg" height="175" id="mymovie" name="mymovie" quality="high" src="<?php echo BASE_URL ?>/public/files/player.swf" type="application/x-shockwave-flash" width="175" wmode="transparent">
                
            </td>
            <td><?php echo $video->video_title; ?></td>
            <td><?php echo $video->video_description; ?></td>
            <td>
                <a class="error" href="<?php echo $this->url("video/edit/$video->video_id"); ?>">Sửa</a>
                | 
                <a class="error" onclick="del(<?php echo $video->video_id ?>)" >Xóa</a>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
</script>