<div style="background: #fff; padding: 5px">
<h2>
			INCENSE POWDER
            International export 
			</h2>
			Our Incense Powder is originally from Quy Nhon - Binh Dinh, Vietnam with high quality and low price, reserving for making all relevant kinds of Incense Stick.  

            <center>
            	<img src="<?php echo BASE_URL ?>/public/images/incense.jpg">
            </center>
</div>            