<!DOCTYPE html <?php echo BASE_URL ?>/public "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title><?php echo isset($title) ? $title : null ?> - Tan Cang - Central Viet Nam</title>
  <meta name="keywords" content="Logistics, Xuất Khẩu, Nhập Khẩu, Xuất Nhập Khẩu, Vận Chuyển Hàng Hóa, Vận Chuyển, Hàng Siêu Trọng, Salan, Xà Lan, Sà Lan, Vận Chuyển Sà Lan, Thủ Tục Hải Quan, Hải Quan, Thông Quan, Mở Tờ Khai, Hun Trùng, Đóng Cont, Đóng Hàng, Forwarder, Stufffing, Unstuffing, Export, Import, Terminal, Port, Sea Port, Transhit, Transhipment, OOG, Over Weight, Over Hight, Over Length, Barge, Barging, Barge team, Barge Fleet, Inland Water Way, IWW, Ship, Vessel, Canoe, River, Channal, Pilot, Boarding Agent, Đại lý tàu, Husbanding Agent, Cambudia, Barging Service, Customs, Customs transhipment, Customs Clearance, EDI, Manifest, E-Manifest, chỉnh sửa Manifest, Adjust Manifest, Inbound, Outbound, Cargo, container, 20', 40', Reefer container, Flatrach, Tank, Hàng Quá Khổ, Cấm Tải, Chất lượng,">
  <meta name="description" content="<?php echo isset($title) ? $title.' - ' : null ?>Logistics - Vận chuyển - Thủ tục hải quan - Manifest - Container">
  <meta name="generator" content="Tan Cang Mien Trung">
  <meta http-equiv="content-language" content="vi,en" />
  <link rel="alternate" href="<?php echo BASE_URL ?>" hreflang="vi-vn" />
  <link href="<?php BASE_URL ?>/public/img/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon">
  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/style.css">
	<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/default.css">
	<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/bootstrap-responsive.min.css">
  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/js/ui/jquery-ui.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery-1.7.2.min.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/ui/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/html5.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.form.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.validate.min.js"></script>
	<script type="text/javascript" src="<?php BASE_URL ?>/public/js/custom.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/localization/messages_vi.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/bootstrap.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/bootstrap.min.js"></script>
</head>

<body>
  <div class="Module">
      <a class="show-ctfrm" href="<?php echo $this->url('quotation') ?>">
          <img alt="Quotation" src="<?php echo BASE_URL ?>/public/img/baogia.png" title="Quotation" height="133px">
      </a>
  </div>
  <div id="container">
    <header>
      <div id="ribbon">
        <div class="site-image-title">
          <h2 style="padding-top:5px">
            
            <table>
              <tbody><tr>
                <td>
                  <a href="<?php echo $this->url(""); ?>"><img src="<?php echo BASE_URL ?>/public/img/logo-tcmt.png"></a>
                </td>
                
              </tr>
            </tbody></table>
          </h2>       
        </div>
        <div class="s4-trc-container-menu">
          <span><a href="<?php echo $this->url(""); ?>" style="color:#fff">Home</a><span style="color:white">&nbsp;|&nbsp;</span>
          <a href="<?php echo $this->url(""); ?>" style="color:#fff">Site map</a><span style="color:white">&nbsp;|&nbsp;</span>

          
          </span>
          <?php if(!isset($_SESSION['userid_logined'])){ ?>
          <a id="ctl00_IdWelcome_ExplicitLogin" class="s4-signInLink" href="<?php echo $this->url("user/login"); ?>" style="display:inline;">Login</a>
          <?php }else{ ?>
          <a id="ctl00_IdWelcome_ExplicitLogin" class="s4-signInLink" href="<?php echo $this->url("user/logout"); ?>" style="display:inline;">Logout</a>
          <?php } ?>
          <br>
          <div style="text-align:right; padding-top:5px">
            <table style="float:right">
              <tbody><tr>
                <td>
                  <img src="<?php echo BASE_URL ?>/public/images/flag_vi.png" alt="Tiếng Việt">
                </td>
                <td>
                  <a href="http://tancangmientrung.local"><span style="color:white; font-size:11px">Tiếng Việt</span></a>
                </td>
              </tr>
            </tbody></table>
          </div>
        </div>
      </div>
      <div id="menu">
        <ul>
          <?php
          if (isset($menus)) {
          foreach ($menus as $menu) {
                if($menu->menu_parent == 0){
                  if ($menu->menu_id == 7) {
                      echo '<li><a href="#">Import - Export</a>
                          <ul>
                            <li><a href="'.$this->url('tapioca-chips').'">Tapioca Chips</a></li>
                            <li><a href="'.$this->url('chili-powder').'">Chili Powder</a></li>
                            <li><a href="'.$this->url('incense-powder').'">Incense Powder</a></li>
                            <li><a href="'.$this->url('sugar').'">Sugar</a></li>
                            <li><a href="'.$this->url('wood-pellets').'">Wood Pellets</a></li>
                            <li><a href="'.$this->url('coffee').'">Coffee bean</a></li>
                            <li><a href="'.$this->url('tea').'">Tea</a></li>
                          </ul>
                      </li>';
                    }

                    echo '<li><a href="'.$this->url('page/'.$menu->menu_id).'">'.$menu->menu_name.'</a>';
                    echo '<ul>';
                    if($menu->menu_id != 5 && $menu->menu_id != 6){
                      foreach ($menus as $menu_child) {
                          if($menu_child->menu_parent == $menu->menu_id){
                              echo '<li><a href="'.$this->url('page/'.$menu_child->menu_id).'">'.$menu_child->menu_name.'</a></li>';
                          }
                      }
                    }
                    echo '</ul></li>';
                }
            }
          }
          ?>
          
        </ul>
      </div>
    </header>
    <div id="wrapper">
      <div id="slider">
        <div id="divMain" style="height: 250px">
          <div id="divShow_1" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 1; background: url(<?php echo BASE_URL ?>/public/images/b2.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_2" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b3.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_3" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b4.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_4" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b5.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_5" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b6.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_6" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b7.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_7" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b8.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_8" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b9.png) no-repeat;">
            &nbsp;</div>
          <div id="divShow_9" style="position: absolute; width: 1000px; height: 250px; vertical-align: bottom; cursor: pointer; opacity: 0; display: none; background: url(<?php echo BASE_URL ?>/public/images/b1.png) no-repeat;">
            &nbsp;</div>
          <div style="position: absolute; margin-top: 215px; width: 410px; margin-left: 560px">
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
              <tbody>
                <tr>
                  <td>
                    &nbsp;</td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_0" name="divPage" onclick="changeSelectImg(this.id, 0);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page_selected.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_1" name="divPage" onclick="changeSelectImg(this.id, 1);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_2" name="divPage" onclick="changeSelectImg(this.id, 2);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_3" name="divPage" onclick="changeSelectImg(this.id, 3);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_4" name="divPage" onclick="changeSelectImg(this.id, 4);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_5" name="divPage" onclick="changeSelectImg(this.id, 5);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_6" name="divPage" onclick="changeSelectImg(this.id, 6);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_7" name="divPage" onclick="changeSelectImg(this.id, 7);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_8" name="divPage" onclick="changeSelectImg(this.id, 8);" style="width: 12px; height: 12px; overflow: hidden; cursor: pointer; background: url(<?php echo BASE_URL ?>/public/images/page.png);">
                      &nbsp;</div>
                  </td>
                  <td nowrap="nowrap" style="padding-left: 6px; width: 12px">
                    <div id="divPage_9" name="divPage" onclick="changeSelectImg(this.id, 8);" style="width: 12px; height: 12px; background: url(<?php echo BASE_URL ?>/public/images/page.png); overflow: hidden; cursor: pointer">
                      &nbsp;</div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div style="position: absolute; margin-top: 19px; width: 450px; margin-left: 550px">
            <span style="font-family: Arial; color: #ffffff"><span style="font-family: Arial; color: #ffff00; font-size: 15px; font-weight: bold">"TOP CONNECTION FOR MULTIMODAL TRANSPORTATION" </span></span>
            <ul style="list-style: square none outside; color: white; font-size: 12px">
              <li>
                <span style="font-family: Arial; color: #ffffff">Terminal/Yard/Warehouse services</span></li>
              <li>
                <span style="font-family: Arial; color: #ffffff">ICD services; Cargo stervedoring/packaging/storing/forwarding services</span></li>
              <li>
                <span style="font-family: Arial; color: #ffffff">Logistics services; customs clearance services</span></li>
              <li>
                <span style="font-family: Arial; color: #ffffff">Inland & marine transportation; tugboat services</span></li>
              <li>
                <span style="font-family: Arial; color: #ffffff">Pilotage & tugboat services</span></li>
              <li>
                <span style="font-family: Arial; color: #ffffff">Container/vessel sanitation & repairing; ship chandlers services</span></li>
              <li>
                <span style="font-family: Arial; color: #ffffff">Maritime services; marine brokerage; vessel agent; shipping agent </span></li>
              <li>
                <span style="font-family: Arial; color: #ffffff">Education and training in marine and logistics </span></li>
                <li>
                <span style="font-family: Arial; color: #ffffff">Import - Export </span></li>
            </ul>
            <span style="font-family: Arial; color: #ffffff"><span style="margin-left: 40px"><a href="<?php echo $this->url('page/1') ?>" style="font-family: Arial; color: #ffff00; font-size: 12px">&gt;&gt; Read more</a> </span></span></div>
        </div>
      </div>

      <div id="main-content">
        <?php echo $content ?>
      </div>
    </div>
  </div>
  <div style="clear:both"></div>
    <footer>
            @<?php echo date('Y') ?> -
            
                <b>TAN CANG - CENTRAL VIET NAM</b>
               &nbsp;
                Address: Hai Cang ward, Qui Nhon city, Binh Dinh province, Viet Nam
                <br>
                Tel: 083 5000 083 - 0932 6789 89 
                &nbsp;
                Email :
                <a href="mailto:cmthanh@saigonnewport.com.vn" tabindex="0">
                    <span style="font-size: 11px; color:blue">cmthanh@saigonnewport.com.vn</span>
                </a>
                -
                <a href="mailto:biz@tancangmientrung.com" tabindex="0">
                    <span style="font-size: 11px; color:blue">biz@tancangmientrung.com</span>
                </a>
    </footer>
  </div>
  <script language="javascript" type="text/javascript">
    function getPosOffset(what, offsettype) {
        var totaloffset = (offsettype == "left") ? what.offsetLeft : what.offsetTop;
        var parentEl = what.offsetParent;
        while (parentEl != null) {
            totaloffset = (offsettype == "left") ? totaloffset + parentEl.offsetLeft : totaloffset + parentEl.offsetTop;
            parentEl = parentEl.offsetParent;
        }
        return totaloffset;
    }
    var numRep = 25;
    var curRep = 0;
    var maxOpac = 1;
    var stepRep = maxOpac / numRep;
    var listDiv = document.getElementsByTagName("div");
    var listItem = new Array();
    var listPageNum = new Array();
    var bgNormal = "url(<?php echo BASE_URL?>/public/images/page.png)";
    var bgSelected = "url(<?php echo BASE_URL?>/public/images/page_selected.png)";
    for (var i = 0; i < listDiv.length; i++) 
    {
        if (listDiv[i].id.indexOf("divShow_") == 0) 
        {
            listItem[listItem.length] = listDiv[i];
            listPageNum[listPageNum.length] = document.getElementById("divPage_" + listPageNum.length);
        }
    }

    var curItem = listItem.length - 1;
    var nextItem = 0;
    var totalImg = listItem.length;
    var intervalID;
    var timeoutID;
    var changing = false;
    function playSlideShow() 
    {
        
        changing = true;
        listItem[nextItem].style.display = "";
        intervalID = window.setInterval("changeOpac()", 40);
    }

    function changeSelectImg(theID, imgIndex) 
    {
        if (imgIndex == curItem) return;
        window.clearInterval(intervalID);
        listPageNum[curItem].style.background = bgNormal;
        listPageNum[parseInt(imgIndex)].style.background = bgSelected;
        if (changing) {
            window.clearInterval(intervalID);
            changing = false;
            if (imgIndex != nextItem) {

                listItem[curItem].style.display = "none";
                listItem[nextItem].style.display = "";
                listItem[curItem].style.opacity = 0;
                listItem[nextItem].style.opacity = 1;
                
                curItem = nextItem;
                nextItem = parseInt(imgIndex);
                if (listItem[nextItem] == null)
                    nextItem = 0;
            }
        }
        else {
            window.clearTimeout(timeoutID);
            nextItem = parseInt(imgIndex);
        }
        playSlideShow();
    }
    function changeOpac() 
    {
        listItem[curItem].style.opacity = maxOpac - stepRep * curRep;
        listItem[nextItem].style.opacity = stepRep * curRep;

        curRep += 1;
        if (curRep > numRep) 
        {
            
            curRep = 0;
            listItem[curItem].style.display = "none";
            listPageNum[curItem].style.background = bgNormal;
            listPageNum[nextItem].style.background = bgSelected;
            
            curItem = nextItem;
            nextItem += 1;
            if (listItem[nextItem] == null)
                nextItem = 0;
            timeoutID = window.setTimeout("playSlideShow()", 3000);
            changing = false;
            window.clearInterval(intervalID);
        }
    }
    playSlideShow();
</script>
</body>
</html>