<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#add").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
				}
					 
				 
			});
	
});
</script>
<div class="login_form">
  <div class="goback"><a href="<?php echo $this->url('album') ?>">&larr;</a></div>      
        <div class="login_body">
          <h1>THÊM ALBUM</h1>
              <form id="add" method="post" action="" enctype="multipart/form-data">
                  <table style="margin-top:20px;">
                    <tr>
                        <td>Tên album </td>
                        <td><input type="text" id="album_name" name="album_name" tabindex="1" autofocus required="required"></td>
                        
                    </tr>
                    <tr>
                      <td>Chọn hình ảnh</td>
                      <td><input type="file" name="image_link[]" id="image_link" required="required" multiple="multiple"></td>
                    </tr>
                    
                     <tr>
                        <td ><input type="reset" name="reset" value="Nhập lại" tabindex="4"></td>
                         <td><input type="submit" name="submit" value="Hoàn tất" tabindex="3"></td>
                         
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
        </div>

