
<?php
$url_order = 'DESC';
if ($order_by == 'album_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
if ($order_by == 'album_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

$i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> DANH SÁCH HÌNH ẢNH </h1></center>
<div class="add-box"><a class="add_button" href="<?php
echo $this->url('image/add/'.$id_album);
?>">Thêm ảnh mới vào album</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
    
    	
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action_img();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="2">Hiển thị 2 giá trị</option>
            <option value="5">Hiển thị 5 giá trị</option>
            <option value="8">Hiển thị 8 giá trị</option>
            <option selected="selected" value="10">Hiển thị 10 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>
      </div>
   
<table class="table_data">
<thead>
    <tr>
    	<th><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th><a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','image_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'image_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','image_link','<?php echo $url_order ?>')">Hình ảnh <?php if ($order_by == 'image_link'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','album_name','<?php echo $url_order ?>')">Tên album <?php if ($order_by == 'album_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
            
           
        <th>&nbsp;</th>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($images as $image) : ?>
        <tr id="<?php echo $image->image_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $image->image_id ?>"></td>
            <td><?php echo $i++; ?></td>
            <td><img src="<?php echo ($image->image_link!=null)?BASE_URL.'/public/images/upload/'.$image->image_link : BASE_URL.'/public/images/img-blank.png'; ?>" width="50px" height="50px" /></td>
            <td>
            <td><?php echo $image->album_name; ?></td>
            
            <td>
                <a class="error" href="<?php echo BASE_URL.'/public/images/upload/'.$image->image_link ?>">Xem</a>
                | 
                <a class="error" onclick="del_img(<?php echo $image->image_id ?>)" >Xóa</a>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
</div>
<script type="text/javascript">
    function del_img(id)
{
  if($('.add-field') !== null)
  {
    $('.add-field').fadeOut();
  }
  var r = confirm("Bạn có chắc chắn muốn xóa không?");
  if (r == true){
    $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
    $.post("<?php echo BASE_URL ?>/image/delete", {data: id},
       function(data){
        if (data.trim() != 'Bạn không có quyền thực hiện thao tác này') {
          $('tr#'+id).remove(); 
          $('#loading').fadeOut(500); 
        };
        $('#loading').fadeOut(500);
        
       
       }); 
  }
}

function action_img(){
  
    var action       = $('#action').attr('value');
    if(action != -1)
    {
      if($('.add-field') !== null)
        {
          $('.add-field').fadeOut();
        }
      var del = [];
      ids = $('input:checkbox.checkbox:checked').map(function() { return del.push(this.value); });
      
       if(action=='delete'){
         var r = confirm("Bạn có chắc chắn muốn xóa không?");
        if (r == true){
          $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
           $.ajax({
            url: "<?php echo BASE_URL ?>/image/delete",   
            type: 'POST',   
            data: "xoa="+del,   
            success:function(answer){ 
              for(var i=0; i<del.length; i++)
                 $('tr#'+del[i]).remove();
              $('#loading').fadeOut(500); 
            }
          });
        }
       }
       
    }
  
}
</script>