<div style="background: #fff; padding: 5px">
<h2>
            WOOD PELLETS
            </h2>
            With the cost of fossil fuels is expected to continue to increase, the demand for pellet heating systems and wood pellets has exploded in recent years. New heating system continuously developed to suit the needs of the consumer. The wood pellets heating systems new advantages than other home heating. Wood pellets heating operation easier and more convenient than using conventional heating in terms of heating needs more frequent maintenance.

            <center>
                <img src="<?php echo BASE_URL ?>/public/images/wood.jpg">
            </center>
</div>            