<div style="background: #fff; padding: 5px">
<h2>
			WHITE SUGAR
			</h2>
			<p>
                With the active support of our team of experts, we are engaged in offering a huge array of Sugar. This superior grade Sugar offered by us is highly applauded for their purity, taste and sweetness. We offer this sugar in secure and tamper proof packaging that is highly demanded in the industry.  
            </p>
            <p>
                Sugar an important food also commonly known as sucrose is white crystalline substance, tastes sweet, a carbohydrate and 100% soluble in water. We are one of the ace White Sugar Suppliers in Vietnam. Sugar as a basic food carbohydrate primarily comes from sugar cane and from sugar beet, but also appears in fruit, honey, sorghum, sugar maple (in maple syrup), and in many other sources.We are counted among the major Raw Sugar Exporters from Vietnam.
            </p>

            <center>
            	<img src="<?php echo BASE_URL ?>/public/images/sugar.jpg">
            </center>
</div>            